package dev.wolly.dsbmaterial.ui.theme

import androidx.compose.ui.graphics.Color

// Default Material 3 Light Fallback (Neutral Blue/Grey)
val md_theme_light_primary = Color(0xFF0061A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
val md_theme_light_secondary = Color(0xFF535F70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)

// Default Material 3 Dark Fallback
val md_theme_dark_primary = Color(0xFF9FCAFF)
val md_theme_dark_onPrimary = Color(0xFF003258)
val md_theme_dark_primaryContainer = Color(0xFF00497D)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_secondary = Color(0xFFBBC7DB)
val md_theme_dark_onSecondary = Color(0xFF253140)

// === GREEN (DSB default, source: #476810) ===
val green_primary = Color(0xFFACD370)
val green_onPrimary = Color(0xFF213600)
val green_primaryContainer = Color(0xFF324F00)
val green_onPrimaryContainer = Color(0xFFC7F089)
val green_secondary = Color(0xFFC0CAAC)
val green_onSecondary = Color(0xFF2B331E)
val green_secondaryContainer = Color(0xFF414A32)
val green_onSecondaryContainer = Color(0xFFDCE7C7)
val green_tertiary = Color(0xFFA0D0CA)
val green_onTertiary = Color(0xFF003734)
val green_tertiaryContainer = Color(0xFF1F4E4A)
val green_onTertiaryContainer = Color(0xFFBCECE6)
val green_background = Color(0xFF1B1C18)
val green_onBackground = Color(0xFFE4E3DB)
val green_surface = Color(0xFF1B1C18)
val green_onSurface = Color(0xFFE4E3DB)
val green_surfaceVariant = Color(0xFF45483D)
val green_onSurfaceVariant = Color(0xFFC5C8B9)
val green_outline = Color(0xFF8F9285)

// === BLUE (source: #0061A4) ===
val blue_primary = Color(0xFF9FCAFF)
val blue_onPrimary = Color(0xFF003258)
val blue_primaryContainer = Color(0xFF00497D)
val blue_onPrimaryContainer = Color(0xFFD1E4FF)
val blue_secondary = Color(0xFFBBC7DB)
val blue_onSecondary = Color(0xFF253140)
val blue_secondaryContainer = Color(0xFF3B4858)
val blue_onSecondaryContainer = Color(0xFFD7E3F8)
val blue_tertiary = Color(0xFFD7BEE4)
val blue_onTertiary = Color(0xFF3B2948)
val blue_tertiaryContainer = Color(0xFF523F5F)
val blue_onTertiaryContainer = Color(0xFFF3DAFF)
val blue_background = Color(0xFF1A1C1E)
val blue_onBackground = Color(0xFFE2E2E6)
val blue_surface = Color(0xFF1A1C1E)
val blue_onSurface = Color(0xFFE2E2E6)
val blue_surfaceVariant = Color(0xFF43474E)
val blue_onSurfaceVariant = Color(0xFFC3C6CF)
val blue_outline = Color(0xFF8D9199)

// === PURPLE (source: #7B4F9B) ===
val purple_primary = Color(0xFFE2B6FF)
val purple_onPrimary = Color(0xFF471868)
val purple_primaryContainer = Color(0xFF5F3280)
val purple_onPrimaryContainer = Color(0xFFF3DAFF)
val purple_secondary = Color(0xFFD2C1D9)
val purple_onSecondary = Color(0xFF372C3F)
val purple_secondaryContainer = Color(0xFF4F4256)
val purple_onSecondaryContainer = Color(0xFFEEDCF5)
val purple_tertiary = Color(0xFFF4B7BA)
val purple_onTertiary = Color(0xFF4C2528)
val purple_tertiaryContainer = Color(0xFF663B3E)
val purple_onTertiaryContainer = Color(0xFFFFDADB)
val purple_background = Color(0xFF1D1B1E)
val purple_onBackground = Color(0xFFE7E1E5)
val purple_surface = Color(0xFF1D1B1E)
val purple_onSurface = Color(0xFFE7E1E5)
val purple_surfaceVariant = Color(0xFF4B454D)
val purple_onSurfaceVariant = Color(0xFFCDC3CE)
val purple_outline = Color(0xFF968E98)

// === RED (source: #BA1A1A) ===
val red_primary = Color(0xFFFFB4AB)
val red_onPrimary = Color(0xFF690004)
val red_primaryContainer = Color(0xFF930009)
val red_onPrimaryContainer = Color(0xFFFFDAD5)
val red_secondary = Color(0xFFE7BDB7)
val red_onSecondary = Color(0xFF442926)
val red_secondaryContainer = Color(0xFF5D3F3C)
val red_onSecondaryContainer = Color(0xFFFFDAD5)
val red_tertiary = Color(0xFFE0C38C)
val red_onTertiary = Color(0xFF3F2E04)
val red_tertiaryContainer = Color(0xFF574419)
val red_onTertiaryContainer = Color(0xFFFDDFA6)
val red_background = Color(0xFF201A19)
val red_onBackground = Color(0xFFEDE0DE)
val red_surface = Color(0xFF201A19)
val red_onSurface = Color(0xFFEDE0DE)
val red_surfaceVariant = Color(0xFF534341)
val red_onSurfaceVariant = Color(0xFFD8C2BF)
val red_outline = Color(0xFFA08C8A)

// === ORANGE (source: #8B5000) ===
val orange_primary = Color(0xFFFFB871)
val orange_onPrimary = Color(0xFF4A2800)
val orange_primaryContainer = Color(0xFF6A3C00)
val orange_onPrimaryContainer = Color(0xFFFFDCBE)
val orange_secondary = Color(0xFFE1C1A4)
val orange_onSecondary = Color(0xFF402C18)
val orange_secondaryContainer = Color(0xFF59422D)
val orange_onSecondaryContainer = Color(0xFFFFDCBE)
val orange_tertiary = Color(0xFFC0CC9A)
val orange_onTertiary = Color(0xFF2B3410)
val orange_tertiaryContainer = Color(0xFF414B24)
val orange_onTertiaryContainer = Color(0xFFDCE8B4)
val orange_background = Color(0xFF201B16)
val orange_onBackground = Color(0xFFEBE0D9)
val orange_surface = Color(0xFF201B16)
val orange_onSurface = Color(0xFFEBE0D9)
val orange_surfaceVariant = Color(0xFF51453A)
val orange_onSurfaceVariant = Color(0xFFD5C3B5)
val orange_outline = Color(0xFF9E8E81)

// === CYAN (source: #006A6A) ===
val cyan_primary = Color(0xFF4CDADA)
val cyan_onPrimary = Color(0xFF003737)
val cyan_primaryContainer = Color(0xFF004F4F)
val cyan_onPrimaryContainer = Color(0xFF6FF7F6)
val cyan_secondary = Color(0xFFB0CCCB)
val cyan_onSecondary = Color(0xFF1B3534)
val cyan_secondaryContainer = Color(0xFF324B4B)
val cyan_onSecondaryContainer = Color(0xFFCCE8E7)
val cyan_tertiary = Color(0xFFB3C8E8)
val cyan_onTertiary = Color(0xFF1C314B)
val cyan_tertiaryContainer = Color(0xFF334863)
val cyan_onTertiaryContainer = Color(0xFFD3E4FF)
val cyan_background = Color(0xFF191C1C)
val cyan_onBackground = Color(0xFFE0E3E2)
val cyan_surface = Color(0xFF191C1C)
val cyan_onSurface = Color(0xFFE0E3E2)
val cyan_surfaceVariant = Color(0xFF3F4948)
val cyan_onSurfaceVariant = Color(0xFFBEC9C8)
val cyan_outline = Color(0xFF889392)

// === PINK (source: #984063) ===
val pink_primary = Color(0xFFFFB0CA)
val pink_onPrimary = Color(0xFF5E1034)
val pink_primaryContainer = Color(0xFF7B284B)
val pink_onPrimaryContainer = Color(0xFFFFD9E3)
val pink_secondary = Color(0xFFE2BDC7)
val pink_onSecondary = Color(0xFF422931)
val pink_secondaryContainer = Color(0xFF5A3F48)
val pink_onSecondaryContainer = Color(0xFFFFD9E3)
val pink_tertiary = Color(0xFFEFBC95)
val pink_onTertiary = Color(0xFF48290C)
val pink_tertiaryContainer = Color(0xFF623F20)
val pink_onTertiaryContainer = Color(0xFFFFDCC2)
val pink_background = Color(0xFF201A1C)
val pink_onBackground = Color(0xFFEBE0E1)
val pink_surface = Color(0xFF201A1C)
val pink_onSurface = Color(0xFFEBE0E1)
val pink_surfaceVariant = Color(0xFF514347)
val pink_onSurfaceVariant = Color(0xFFD5C2C6)
val pink_outline = Color(0xFF9E8C90)
